repository: monasca/notification
variants:

  - tag: master
    aliases:
      - :latest
      - :master-{date}-{time}
    args:
      NOTIFICATION_BRANCH: refs/changes/17/461917/3
      TIMESTAMP_SLUG: 20170809-155207
