version: '3'
services:

  memcached:
    image: memcached:${MEMCACHED_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=memcached"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always

  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=influxdb"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always
 
  influxdb-init:
    image: monasca/influxdb-init:${INFLUXDB_INIT_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=influxdb-init"
    depends_on:
      - influxdb

  # cadvisor will allow host metrics to be collected, but requires significant
  # access to the host system
  # if this is not desired, the following can be commented out, and the CADVISOR
  # environment variable should be set to "false" in the `agent-collector`
  # block - however no metrics will be collected
  cadvisor:
    image: google/cadvisor:${CADVISOR_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=cadvisor"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always

  agent-forwarder:
    image: monasca/agent-forwarder:${MON_AGENT_FORWARDER_VERSION}
    environment:
      NON_LOCAL_TRAFFIC: "true"
      LOGSTASH_FIELDS: "service=monasca-agent-forwarder"
      OS_AUTH_URL: "http://10.81.1.79:5000/v3"
      OS_USERNAME: "monasca-agent"
      OS_PASSWORD: "123"
      OS_PROJECT_NAME: "mini-mon"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always

  agent-collector:
    image: monasca/agent-collector:${MON_AGENT_COLLECTOR_VERSION}
    restart: on-failure
    environment:
      AGENT_HOSTNAME: "docker-host"
      FORWARDER_URL: "http://agent-forwarder:17123"
      CADVISOR: "true"
      CADVISOR_URL: "http://cadvisor:8080/"
      LOGSTASH_FIELDS: "service=monasca-agent-collector"
      MONASCA_MONITORING: "true"
      MONASCA_LOG_MONITORING: "true"
      OS_AUTH_URL: "http://10.81.1.79:5000/v3"
      OS_USERNAME: "monasca-agent"
      OS_PASSWORD: "123"
      OS_PROJECT_NAME: "mini-mon"
    cap_add:
      - FOWNER
    volumes:
      - "/:/rootfs:ro"
      - "/etc/localtime:/etc/localtime:ro"

  alarms:
    image: monasca/alarms:${MON_ALARMS_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-alarms"
      OS_AUTH_URL: "http://10.81.1.79:5000/v3"
      OS_USERNAME: "monasca-agent"
      OS_PASSWORD: "123"
      OS_PROJECT_NAME: "mini-mon"
    depends_on:
      - monasca
    volumes:
    - "/etc/localtime:/etc/localtime:ro"

  zookeeper:
    image: zookeeper:${ZOOKEEPER_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=zookeeper"
    restart: on-failure
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always

  kafka:
    image: monasca/kafka:${MON_KAFKA_VERSION}
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      LOGSTASH_FIELDS: "service=kafka"
    restart: on-failure
    depends_on:
      - zookeeper
    volumes:
    - "/etc/localtime:/etc/localtime:ro"

  kafka-watcher:
    image: monasca/kafka-watcher:${MON_KAFKA_WATCHER_VERSION}
    environment:
      BOOT_STRAP_SERVERS: "kafka"
      PROMETHEUS_ENDPOINT: "0.0.0.0:8080"
      LOGSTASH_FIELDS: "service=kafka-watcher"
    depends_on:
      - kafka
    ports:
      - "18080:8080"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always

  kafka-init:
    image: monasca/kafka-init:${MON_KAFKA_INIT_VERSION}
    environment:
      ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
      KAFKA_TOPIC_CONFIG: segment.ms=900000 # 15m
      KAFKA_CREATE_TOPICS: "\
        metrics:64:1,\
        alarm-state-transitions:12:1,\
        alarm-notifications:12:1,\
        retry-notifications:3:1,\
        events:12:1,\
        kafka-health-check:1:1,\
        60-seconds-notifications:3:1"
      LOGSTASH_FIELDS: "service=kafka-init"
    depends_on:
      - zookeeper

  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: secretmysql
      LOGSTASH_FIELDS: "service=mysql"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always
  mysql-init:
    image: monasca/mysql-init:${MYSQL_INIT_VERSION}
    environment:
      MYSQL_INIT_DISABLE_REMOTE_ROOT: "false"
      MYSQL_INIT_RANDOM_PASSWORD: "false"
      LOGSTASH_FIELDS: "service=mysql-init"

  monasca-sidecar:
    image: timothyb89/monasca-sidecar:${MON_SIDECAR_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-sidecar"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always

  monasca:
    image: monasca/api:${MON_API_VERSION}
    environment:
      SIDECAR_URL: http://monasca-sidecar:4888/v1/ingest
      LOGSTASH_FIELDS: "service=monasca-api"
      KEYSTONE_IDENTITY_URI: "http://10.81.1.79:5000"
      KEYSTONE_AUTH_URI: "http://10.81.1.79:5000"
      KEYSTONE_ADMIN_USER: "admin"
      KEYSTONE_ADMIN_PASSWORD: "ifvJAZJQEg3LxxyvLg7Xc5Fu3"
      KEYSTONE_INSECURE: "true"
      KEYSTONE_REGION_NAME: "regionOne"
    depends_on:
      - influxdb
      - mysql
      - zookeeper
      - kafka
      - monasca-sidecar
      - memcached
    ports:
      - "8070:8070"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always

  monasca-persister:
    image: monasca/persister:${MON_PERSISTER_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-persister"
    restart: on-failure
    depends_on:
      - monasca
      - influxdb
      - zookeeper
      - kafka
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
  thresh:
    image: monasca/thresh:${MON_THRESH_VERSION}
    environment:
      NO_STORM_CLUSTER: "true"
      WORKER_MAX_HEAP_MB: "256"
      LOGSTASH_FIELDS: "service=monasca-thresh"
    depends_on:
      - zookeeper
      - kafka
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always

  monasca-notification:
    image: monasca/notification:${MON_NOTIFICATION_VERSION}
    environment:
      NF_PLUGINS: "webhook"
      LOGSTASH_FIELDS: "service=monasca-notification"
      STATSD_HOST: monasca-statsd
      STATSD_PORT: 8125
    depends_on:
      - monasca
      - zookeeper
      - kafka
      - mysql
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always

  grafana:
    image: monasca/grafana:${MON_GRAFANA_VERSION}
    environment:
      GF_AUTH_BASIC_ENABLED: "true"
      GF_USERS_ALLOW_SIGN_UP: "true"
      GF_USERS_ALLOW_ORG_CREATE: "true"
      GF_AUTH_KEYSTONE_ENABLED: "true"
      GF_AUTH_KEYSTONE_AUTH_URL: "http://10.81.1.79:5000"
      GF_AUTH_KEYSTONE_VERIFY_SSL_CERT: "false"
      GF_AUTH_KEYSTONE_CREDENTIAL_AES_KEY: "ifvJAZJQEg3LxxyvLg7Xc5Fu3"
      GF_AUTH_KEYSTONE_DEFAULT_ROLE: "Default"
      GF_AUTH_KEYSTONE_DEFAULT_DOMAIN: "Default"
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp.gmail.com:587"
      GF_SMTP_USER: "mghani828@gmail.com"
      GF_SMTP_PASSWORD: "Jx2pn407z"
      GF_SMTP_FROM_ADDRESS: "mghani828@gmail.com"
      LOGSTASH_FIELDS: "service=grafana"
    ports:
      - "3000:3000"
    depends_on:
      - monasca
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always

  grafana-init:
    image: monasca/grafana-init:${MON_GRAFANA_INIT_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=grafana-init"
      GRAFANA_USERNAME: "grafana-admin"
      GRAFANA_PASSWORD: "admin"
      DATASOURCE_AUTH: "Token"
      DATASOURCE_AUTH_TOKEN: "gAAAAABgC9GwGWY7-Rt_NAz-qmItV81P8ElPvrGmbnK9YJfl2Cz-pEHnSm-c0XTJQwDFxRB01v01ata-ykgQ_gXYGkFipggx4gX4eK6lDVr2zn4EASEKvwMiEAROM2nYZq2BtJUKGEt1Dk7V24P5lVB07-p4m0q2mvrd3rllnDZGP-ld8YlyOhM"
    depends_on:
      - grafana
    volumes:
    - "/etc/localtime:/etc/localtime:ro"

  monasca-statsd:
    image: monasca/statsd:${MON_STATSD_VERSION}
    environment:
      FORWARDER_URL: http://agent-forwarder:17123
      LOG_LEVEL: WARN
    ports:
      - "8125/udp"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    restart: always
