version: '3'
services:

  log-metrics:
    image: monasca/log-metrics:${MON_LOG_METRICS_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-log-metrics"
    depends_on:
      - kafka
      - zookeeper
      - log-transformer

  log-persister:
    image: monasca/log-persister:${MON_LOG_PERSISTER_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-log-persister"
    depends_on:
      - kafka
      - zookeeper
      - elasticsearch
      - log-transformer

  log-transformer:
    image: monasca/log-transformer:${MON_LOG_TRANSFORMER_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-log-transformer"
    depends_on:
      - kafka
      - zookeeper
      - log-api

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - cluster.name=monasca
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - ES_HEAP_SIZE=1g
      - LOGSTASH_FIELDS="service=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  elasticsearch-init:
    image: monasca/elasticsearch-init:${MON_ELASTICSEARCH_INIT_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=elasticsearch-init"
    volumes:
      - ./elasticsearch-templates/logs.template:/templates/logs.json
    depends_on:
      - elasticsearch
  elasticsearch-curator:
    image: monasca/elasticsearch-curator:${MON_ELASTICSEARCH_CURATOR_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=elasticsearch-curator"
    depends_on:
      - elasticsearch

  kafka-log-init:
    image: monasca/kafka-init:${MON_KAFKA_INIT_VERSION}
    environment:
      KAFKA_TOPIC_CONFIG: segment.ms=900000 # 15m
      KAFKA_CREATE_TOPICS: "\
        log:4:1,\
        log-transformed:4:1"
      LOGSTASH_FIELDS: "service=kafka-log-init"
    depends_on:
      - kafka

  kibana:
    image: monasca/kibana:${MON_KIBANA_VERSION}
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_PINGTIMEOUT: 1000
      KEYSTONE_URI: "http://10.81.1.79:5000"
      LOGSTASH_FIELDS: "service=kibana"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  log-api:
    image: monasca/log-api:${MON_LOG_API_VERSION}
    environment:
      LOGSPOUT: ignore
      LOGSTASH_FIELDS: "service=monasca-log-api"
      STATSD_HOST: monasca-statsd
      STATSD_PORT: 8125
      KEYSTONE_IDENTITY_URI: "http://10.81.1.79:5000"
      KEYSTONE_AUTH_URI: "http://10.81.1.79:5000"
      KEYSTONE_ADMIN_USER: "admin"
      KEYSTONE_ADMIN_PASSWORD: "ifvJAZJQEg3LxxyvLg7Xc5Fu3"
      KEYSTONE_INSECURE: "true"
      KEYSTONE_REGION_NAME: "regionOne"
    depends_on:
      - zookeeper
      - kafka
      - memcached
    ports:
      - "5607:5607"

  log-agent:
    image: monasca/log-agent:${MON_LOG_AGENT_VERSION}
    environment:
      LOGSPOUT: ignore
      LOGSTASH_FIELDS: "service=monasca-log-agent"
    depends_on:
      - log-api
    ports:
      - "5610:5610"
  logspout:
    image: monasca/logspout:${MON_LOGSPOUT_VERSION}
    environment:
      LOGSPOUT: ignore
      LOGSTASH_FIELDS: "service=logspout"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: on-failure
    depends_on:
        - log-agent
