---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app-demo
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app-demo
        metric_endpoint: prometheus
    spec:
      containers:
      - name: web-app-demo
        image: kaiyansheng/django_docker:latest
        ports:
        - name: django
          containerPort: 8000
        - name: prometheus
          containerPort: 8005
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-demo
  namespace: monitoring
  labels:
    app: web-app-demo
    metric_endpoint: prometheus
spec:
  ports:
  - name: django
    port: 8000
  - name: prometheus
    port: 8005
  selector:
    app: web-app-demo