repository: monasca/storm
variants:
  - tag: 1.1.1-1.0.13
    aliases:
      - :latest
      - :1.1.1
    args:
      STORM_VERSION: 1.1.1

  - tag: 1.0.3-1.0.11
    aliases:
      - :1.0.3
    args:
      STORM_VERSION: 1.0.3
