repository: monasca/kafka
variants:
  - tag: 0.9.0.1-2.11-1.1.8
    args:
      KAFKA_VERSION: "0.9.0.1"
      SCALA_VERSION: "2.11"

      # it seems kafka 0.9.x has been removed from mirrors...
      MIRROR: 'http://archive.apache.org/dist/'
      ASC_MIRROR: 'http://archive.apache.org/dist/kafka'
      DIRECT: 'true'
